<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>NuciGenerators.Text</RootNamespace>
    <Version>1.0.1</Version>
    <Description>Core text generation primitives for the NuciGenerators.Text.* packages.</Description>
    <Authors>Horațiu Mlendea</Authors>
    <Copyright>Copyright 2026 © Horațiu Mlendea</Copyright>
    <RepositoryUrl>https://github.com/hmlendea/nucigenerators.text</RepositoryUrl>
    <PackageLicenseExpression>GPL-3.0-or-later</PackageLicenseExpression>
    <PackageTags>Text TextGeneration TextGenerators Generators</PackageTags>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <ImplicitUsings>disable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="NuciExtensions" Version="5.3.1" />
  </ItemGroup>

</Project>